version: "3.4"
services:
  #db:
  # container_name: code-arena-db-full
  # image: gabrielgouv/postgres-code-arena
  # restart: always
  # build:
  #   context: ./code-arena-api/database
  #   dockerfile: Dockerfile
  # environment:
  #   TZ: America/Sao_Paulo
  #   POSTGRES_USER: postgres
  #   POSTGRES_PASSWORD: test
  #   POSTGRES_DB: codearena_test
  # ports:
  #   - "5430:5432"
  # networks:
  #   - code-arena-network
  # flyway:
  #   image: flyway/flyway
  #   command: -url=jdbc:postgresql://db:5432/codearena_test -schemas=public -user=postgres -password=test -connectRetries=10 migrate
  #   volumes:
  #     - ./code-arena-migration/:/flyway/sql
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   networks:
  #     - code-arena-network
  code-arena-api:
    container_name: code-arena-api-full
    image: gabrielgouv/code-arena
    restart: always
    build:
      context: ./code-arena-api
      dockerfile: Dockerfile
    working_dir: /code-arena
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Development
      SPRING_PROFILES_ACTIVE: dockerdev
    ports:
      #   - "8081:8081"
      - "5006:5006"
    command: "sh startup.sh"
    # links:
    #   - db
    # depends_on:
    #   - db
    networks:
      - code-arena-network
  code-arena-auth-server:
    container_name: code-arena-auth-server
    image: gabrielgouv/code-arena-auth-server
    restart: always
    build:
      context: ./code-arena-auth-server
      dockerfile: Dockerfile
    working_dir: /code-arena
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Development
      SPRING_PROFILES_ACTIVE: dockerdev
    ports:
      - "8090:8090"
      - "5007:5007"
    command: "sh startup.sh"
    # links:
    #   - db
    # depends_on:
    #   - db
    networks:
      - code-arena-network
  code-arena-api-gateway:
    container_name: code-arena-api-gateway-full
    image: gabrielgouv/code-arena-api-gateway
    restart: always
    build:
      context: ./code-arena-api-gateway
      dockerfile: Dockerfile
    working_dir: /code-arena
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Development
      SPRING_PROFILES_ACTIVE: dockerdev
    ports:
      - "8080:8080"
      - "5005:5005"
    command: "sh startup.sh"
    links:
      - code-arena-api
    networks:
      - code-arena-network
networks:
  code-arena-network:
    driver: bridge
