version: '3.4'
services:
  db:
    container_name: code-arena-db-full
    image: gabrielgouv/postgres-code-arena
    restart: always
    build:
      context: ./code-arena-server/database
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: codearena_test
    ports:
      - "5430:5432"
    networks:
      - code-arena-network
  code-arena-server:
    container_name: code-arena-server-full
    image: gabrielgouv/code-arena
    restart: always
    build:
      context: ./code-arena-server
      dockerfile: Dockerfile
    working_dir: /code-arena
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Development
    ports:
    #   - "8081:8081"
      - "5006:5006"
    command: 'sh startup.sh'
    links:
      - db
    depends_on:
      - db
    networks:
      - code-arena-network
  code-arena-api-gateway:
    container_name: code-arena-api-gateway-full
    image: gabrielgouv/code-arena-api-gateway
    restart: always
    build:
      context: ./code-arena-api-gateway
      dockerfile: Dockerfile
    working_dir: /code-arena
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Development
    ports:
      - "8080:8080"
      - "5005:5005"
    command: 'sh startup.sh'
    links:
      - code-arena-server
    networks:
      - code-arena-network
networks:
  code-arena-network:
    driver: bridge
