zuul:
  routes:
    api:
      url: http://code-arena-api:8081/api
    auth:
      path: /login/**
      stripPrefix: false
      url: http://code-arena-auth-server:8090/login
server:
  port: 8080
code-arena:
  security:
    jwt:
      secret: asupersecretpassword
      url: /login
      header: Authorization
      prefix: Bearer