version: '3.4'
services:
  db:
    container_name: code-arena-db
    image: gabrielgouv/postgres-code-arena
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: codearena_test
    ports:
      - "5430:5432"
    networks:
      - code-arena-network
  code-arena:
    container_name: code-arena-server
    image: gabrielgouv/code-arena
    restart: always
    build: .
    working_dir: /code-arena
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Development
    ports:
      - "8080:8080"
      - "5005:5005"
    command: 'sh startup.sh'
    links:
      - db
    depends_on:
      - db
    networks:
      - code-arena-network
networks:
  code-arena-network:
    driver: bridge
