-- START TABLE USERS
INSERT INTO users (id, creation_date, deletion_date, date_of_birth, username, email, first_name, last_name, password, user_role) VALUES (1, '2019-11-14 14:34:53.272000', null, '1997-04-03', 'gabrielgouv', 'joao@gmail.com', 'João Gabriel', 'Gouveia', '$2a$16$McLguCeVXJ7KIaFJH8MnBuI8SfaEE0rnfZds8jRbUdyXrx9YzXIqW', 'USER');
INSERT INTO users (id, creation_date, deletion_date, date_of_birth, username, email, first_name, last_name, password, user_role) VALUES (2, '2019-11-14 14:36:18.814000', null, '1997-04-03', 'lukas.matheus', 'lukas@gmail.com', 'Lukas', 'Matheus', '$2a$16$tw8rz1IEJLc3feg63hS/Sed9zBeYpdIz8e4tQyITYRHEsTl.wwwuS', 'USER');
INSERT INTO users (id, creation_date, deletion_date, date_of_birth, username, email, first_name, last_name, password, user_role) VALUES (3, '2019-11-14 14:37:21.220000', null, '1990-04-03', 'zepauloo', 'zepaulo@gmail.com', 'José Paulo', 'da Silva', '$2a$16$3LZL6cqLpLZz/WuBeGea1OzepYtO.CeFpmOjvyL3lVAW12b5Y8m1y', 'USER');
INSERT INTO users (id, creation_date, deletion_date, date_of_birth, username, email, first_name, last_name, password, user_role) VALUES (4, '2019-11-14 14:38:09.415000', null, '1995-04-03', 'markos95', 'marcos95@hotmail.com', 'Marcos', 'dos Santos', '$2a$16$szP5Q3zcnC8t8NGHPngrxuExzaD/MqnKRgN0VTsasFgt44ZZRpZo6', 'USER');
ALTER SEQUENCE seq_users RESTART WITH 5;
-- END TABLE USERS


-- START TABLE CHALLENGES
INSERT INTO challenges (id, creation_date, deletion_date, content, difficult_level, rating, title, author_id) VALUES (1, '2019-11-14 14:45:55.355000', null, 'Morbi posuere commodo justo, id sodales nisi fringilla vel. Quisque in dui non nibh sollicitudin commodo non sit amet tellus. Maecenas id pellentesque est, id tempor erat. Vivamus vehicula est non turpis laoreet tempus. Duis gravida lorem sed bibendum ornare. Donec cursus eu est interdum finibus. Curabitur turpis tortor, vehicula hendrerit pulvinar sed, viverra in ante. Sed elementum lectus nec magna iaculis cursus. Praesent lacus odio, varius viverra accumsan id, vehicula eget erat. Duis laoreet vel velit non euismod. Nullam maximus aliquet justo eu iaculis. ', 'VERY_EASY', null, 'Desafio 1', 1);
INSERT INTO challenges (id, creation_date, deletion_date, content, difficult_level, rating, title, author_id) VALUES (2, '2019-11-14 14:46:24.874000', null, 'Nam finibus tortor diam, congue pharetra dui tristique et. Nam varius diam ut dapibus aliquet. Vestibulum iaculis augue sed magna finibus, ut efficitur tortor tempus. Aliquam tempor aliquet commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam a ullamcorper orci, ac luctus odio. Maecenas blandit rutrum orci, ut hendrerit est vestibulum a. ', 'HARD', null, 'Desafio 2', 1);
INSERT INTO challenges (id, creation_date, deletion_date, content, difficult_level, rating, title, author_id) VALUES (3, '2019-11-14 14:46:35.334000', null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac tortor urna. Morbi ut eros non orci blandit vestibulum et a est. Sed viverra, turpis id euismod bibendum, purus felis venenatis massa, vel consequat leo tortor eu leo. Duis consequat facilisis hendrerit. Mauris vitae odio porta, varius nisi vitae, venenatis dolor. Aenean orci quam, iaculis quis vestibulum et, volutpat nec dolor. Praesent accumsan ultricies laoreet. Cras sed nulla vitae urna convallis molestie sed quis tortor. ', 'HARD', null, 'Desafio 3', 3);
INSERT INTO challenges (id, creation_date, deletion_date, content, difficult_level, rating, title, author_id) VALUES (4, '2019-11-14 14:46:52.894000', null, 'Morbi posuere commodo justo, id sodales nisi fringilla vel. Quisque in dui non nibh sollicitudin commodo non sit amet tellus. Maecenas id pellentesque est, id tempor erat. Vivamus vehicula est non turpis laoreet tempus. Duis gravida lorem sed bibendum ornare. Donec cursus eu est interdum finibus. Curabitur turpis tortor, vehicula hendrerit pulvinar sed, viverra in ante. Sed elementum lectus nec magna iaculis cursus. Praesent lacus odio, varius viverra accumsan id, vehicula eget erat. Duis laoreet vel velit non euismod. Nullam maximus aliquet justo eu iaculis. ', 'EXPERT', null, 'Desafio 4', 3);
INSERT INTO challenges (id, creation_date, deletion_date, content, difficult_level, rating, title, author_id) VALUES (5, '2019-11-14 14:47:22.032000', null, 'Morbi faucibus erat pellentesque ipsum hendrerit molestie. Suspendisse imperdiet posuere ultrices. Phasellus ullamcorper mi a fringilla dignissim. Vestibulum bibendum molestie pulvinar. Vestibulum eu sollicitudin justo. Mauris porttitor diam ut tincidunt sagittis. Aliquam sed molestie odio. Integer vulputate urna nec augue varius, quis ornare risus eleifend. Phasellus vestibulum enim blandit magna lobortis, et rutrum nunc congue. ', 'VERY_EASY', null, 'Desafio 5', 3);
ALTER SEQUENCE seq_challenges RESTART WITH 6;
-- END TABLE CHALLENGES

