server:
  port: 8090
code-arena:
  security:
    jwt:
      secret: codearena
spring:
  datasource:
    jdbcUrl: jdbc:postgresql://code-arena.cjmxfcpq4sfz.us-east-2.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: adminadmin
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
