server:
  port: 8090
code-arena:
  security:
    jwt:
      secret: codearena
spring:
  datasource:
    jdbcUrl: jdbc:postgresql://db:5432/codearena_test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
