name: Build code-arena-auth
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Mvn clean install in code-arena-auth-server
      working-directory: ./code-arena-auth-server
      run: mvn clean install
