name: Build code-arena-api-gateway
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Mvn clean install in API Gateway project
      working-directory: ./code-arena-api-gateway
      run: mvn clean install
